version: "3"

services:
    httpd:
        container_name: httpd
        image: httpd:alpine3.16
        ports:
          - "8080:80"
        volumes:
          - ./ui/app/out/:/usr/local/apache2/htdocs/
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./resources/docker/local/api/Dockerfile
        tty: true
        ports:
          - "18080:8080"
        volumes:
          - ./api/:/go/src/app/
